//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branche
    {
        public Branche()
        {
            this.Car = new HashSet<Car>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int BrancheId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public int Capacity { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
