//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public int Year { get; set; }
        public decimal Kilometrs { get; set; }
        public string Plate { get; set; }
        public string Photo { get; set; }
        public int BrancheBrancheId { get; set; }
        public int ServiceServiceId { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Service Service { get; set; }
    }
}
