//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public int Year { get; set; }
        public decimal Kilometrs { get; set; }
        public string Plate { get; set; }
        public string Photo { get; set; }
        public int BrancheBrancheId { get; set; }
        public int ServiceServiceId { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Service Service { get; set; }
    }
}
