//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Birthday { get; set; }
        public int PhoneNumber { get; set; }
        public string Address { get; set; }
        public int BrancheBrancheId { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Job Job { get; set; }
    }
}
