//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Car = new HashSet<Car>();
            this.ServiceHistory = new HashSet<ServiceHistory>();
        }
    
        public int ServiceId { get; set; }
        public string ServieType { get; set; }
        public int CustomerCustomerId { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<ServiceHistory> ServiceHistory { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
