//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Car = new HashSet<Car>();
            this.ServiceHistory = new HashSet<ServiceHistory>();
        }
    
        public int ServiceId { get; set; }
        public string ServieType { get; set; }
        public int CustomerCustomerId { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<ServiceHistory> ServiceHistory { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
