//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int ServiceHistoryId { get; set; }
        public decimal Value { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public int ServiceServiceId { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
