//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckWebSite.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TruckCompanyDBContainer : DbContext
    {
        public TruckCompanyDBContainer()
            : base("name=TruckCompanyDBContainer")
        {
            Database.SetInitializer<TruckCompanyDBContainer>(new CreateDatabaseIfNotExists<TruckCompanyDBContainer>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> CarSet { get; set; }
        public DbSet<Branche> BrancheSet { get; set; }
        public DbSet<Employee> EmployeeSet { get; set; }
        public DbSet<Schedule> ScheduleSet { get; set; }
        public DbSet<Job> JobSet { get; set; }
        public DbSet<Service> ServiceSet { get; set; }
        public DbSet<ServiceHistory> ServiceHistorySet { get; set; }
        public DbSet<Customer> CustomerSet { get; set; }
    }
}
